# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad_desc <- function(Y, X, step, dim, itr, n1, n2, Qtrace) {
    .Call('_RcppArma_grad_desc', PACKAGE = 'RcppArma', Y, X, step, dim, itr, n1, n2, Qtrace)
}

